"""
EUDR Due Diligence Statement generator.
Builds a structured DDS JSON + Granite narrative summary.
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime, date

from ..eudr.models import (
    EUDRDueDiligenceStatement, EUDRRiskAssessment,
    EUDRRiskLevel, EUDRPlot,
)
from ..eudr.country_risk import get_country_risk
from ..models.enums import AnalysisType


def generate_dds(
    plot: EUDRPlot,
    assessment: EUDRRiskAssessment,
    operator_name: str | None = None,
) -> EUDRDueDiligenceStatement:
    """Build a complete Due Diligence Statement for a single plot."""
    dds_id = f"DDS-{uuid.uuid4().hex[:8].upper()}"

    # Recommended mitigation measures
    mitigations = _build_mitigations(assessment)

    # Data provenance list
    provenance = list(assessment.deforestation.data_sources)
    provenance.append("WDPA v3 — Protected Planet")
    provenance.append("Oxeous Automated Assessment v0.1 — EU 2023/1115")

    return EUDRDueDiligenceStatement(
        dds_id=dds_id,
        created_at=datetime.utcnow().isoformat() + "Z",
        operator_name=operator_name,
        commodity=plot.commodity,
        country_of_production=plot.country_name,
        reference_period={
            "start": "2020-12-31",
            "end": date.today().isoformat(),
        },
        plots=[assessment],
        overall_status=assessment.overall_risk,
        mitigation_measures=mitigations,
        data_provenance=provenance,
    )


def format_dds_text(dds: EUDRDueDiligenceStatement) -> str:
    """Return a human-readable DDS text for display or PDF generation."""
    r = dds.plots[0] if dds.plots else None
    lines = [
        f"DUE DILIGENCE STATEMENT",
        f"Regulation: {dds.regulation_reference}",
        f"Statement ID: {dds.dds_id}",
        f"Generated: {dds.created_at[:10]}",
        f"Generated by: {dds.generated_by}",
        "",
        f"COMMODITY: {dds.commodity.value.replace('_', ' ').upper()}",
        f"COUNTRY OF PRODUCTION: {dds.country_of_production}",
        f"REFERENCE PERIOD: {dds.reference_period['start']} to {dds.reference_period['end']}",
        f"OPERATOR: {dds.operator_name or 'Not specified'}",
        "",
        f"OVERALL COMPLIANCE STATUS: {dds.overall_status.value.upper().replace('_', ' ')}",
        "",
    ]
    if r:
        lines += [
            f"DEFORESTATION ASSESSMENT",
            f"  Deforestation detected (post Dec 2020): {'YES ⚠' if r.deforestation.has_deforestation else 'NO ✓'}",
            f"  Forest cover at cutoff (Dec 2020): {r.deforestation.forest_cover_2020_pct:.1f}%",
            f"  Post-cutoff forest loss: {r.deforestation.forest_loss_ha:.2f} ha ({r.deforestation.forest_loss_pct:.1f}%)",
            f"  Loss years: {', '.join(str(y) for y in r.deforestation.loss_years) or 'None detected'}",
            f"  Data confidence: {r.deforestation.confidence.upper()}",
            f"  Sources: {', '.join(r.deforestation.data_sources)}",
            "",
            f"LEGALITY ASSESSMENT",
            f"  Protected area overlap: {'YES ⚠' if r.legality.overlaps_protected_area else 'NO ✓'}",
            f"  Country risk: {r.legality.country_risk_level.value.upper()}",
        ]
        if r.legality.issues:
            lines += [f"  Issue: {issue}" for issue in r.legality.issues]
        lines += [
            "",
            f"RISK SCORE: {r.risk_score:.0f}/100",
            f"REQUIRES HUMAN REVIEW: {'YES' if r.requires_human_review else 'NO'}",
            "",
        ]
    if dds.mitigation_measures:
        lines += ["MITIGATION MEASURES:"]
        lines += [f"  {i+1}. {m}" for i, m in enumerate(dds.mitigation_measures)]
        lines.append("")

    lines += [
        f"DATA PROVENANCE:",
        *[f"  - {p}" for p in dds.data_provenance],
        "",
        "This statement was generated automatically by the Oxeous EUDR Platform.",
        "It does not constitute legal advice. Human review is recommended for all",
        "at-risk or non-compliant findings before submission to EU authorities.",
    ]
    return "\n".join(lines)


def _build_mitigations(assessment: EUDRRiskAssessment) -> list[str]:
    measures: list[str] = []
    r = assessment

    if r.deforestation.has_deforestation:
        measures.append(
            "Commission field verification of detected forest loss areas before submitting to EU authorities"
        )
        measures.append(
            "Obtain certified satellite verification from an accredited third-party service"
        )

    if r.legality.overlaps_protected_area:
        measures.append(
            "Verify plot boundaries do not include legally protected areas — contact local land registry"
        )

    if r.legality.country_risk_level.value == "high":
        measures.append(
            "Apply enhanced due diligence: obtain local land-use permits and supply chain certification"
        )
        measures.append(
            "Consider third-party supply chain traceability certification (Rainforest Alliance, FSC, RSPO)"
        )

    if r.deforestation.confidence == "low":
        measures.append(
            "Collect additional high-resolution imagery (Sentinel-2 / Planet) for this plot to improve confidence"
        )

    if not measures:
        measures.append(
            "Maintain documentation of satellite evidence and update assessment annually"
        )

    return measures
